---
abstract: 'Check B<requires> & B<test_requires> of your package for CPAN inclusion.'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::CheckDeps: 0.004
  Test::More: 0.98
  Test::Requires: 0.06
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Midgen
name: App-Midgen
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Test::Pod: 1.48
  Test::Pod::Coverage: 1.08
requires:
  Carp: 1.26
  Cwd: 3.4
  Data::Printer: 0.35
  File::Slurp: 9999.19
  File::Spec: 3.4
  Getopt::Long: 2.39
  JSON::Tiny: 0.28
  List::MoreUtils: 0.33
  MetaCPAN::API: 0.43
  Module::CoreList: 2.91
  Moo: 1.002
  MooX::Types::MooseLike: 0.23
  PPI: 1.215
  PPI::XS: 0.902
  Perl::MinimumVersion: 1.32
  Perl::MinimumVersion::Fast: 0.1
  Perl::PrereqScanner: 1.015
  Pod::Usage: 1.63
  Scalar::Util: 1.27
  Term::ANSIColor: 4.02
  Time::Stamp: 1.3
  Try::Tiny: 0.12
  Type::Tiny: 0.006
  constant: 1.27
  perl: 5.10.1
  version: 0.9902
resources:
  bugtracker: https://github.com/kevindawson/App-Midgen/issues
  homepage: https://github.com/kevindawson/App-Midgen
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kevindawson/App-Midgen.git
version: 0.24
