---
abstract: 'Check B<requires> & B<test_rerquires> of your Package for CPAN inclusion.'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.98
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Midgen
name: App-Midgen
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Test::Pod: 1.46
  Test::Pod::Coverage: 1.08
requires:
  CPAN: 1.9800
  Carp: 1.26
  Cwd: 3.40
  Data::Printer: 0.35
  File::Spec: 3.40
  Getopt::Long: 2.38
  Module::CoreList: 2.82
  Moo: 1.000008
  MooX::Types::MooseLike::Base: 0.22
  PPI: 1.215
  Perl::MinimumVersion: 1.32
  Pod::Usage: 1.61
  Try::Tiny: 0.12
  constant: 1.25
  lib: 0.63
  perl: 5.10.1
  version: 0.9902
resources:
  bugtracker: https://github.com/kevindawson/App-Midgen/issues
  homepage: https://github.com/kevindawson/App-Midgen
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kevindawson/App-Midgen.git
version: 0.12
