---
abstract: 'Check B<requires> & B<test_rerquires> of your Package for CPAN inclusion.'
author:
  - 'Kevin Dawson <bowtie@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
  Test::More: 0.980
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: App::Midgen
name: App-Midgen
no_index:
  directory:
    - inc
    - t
    - xt
recommends:
  Test::Pod: 1.460
  Test::Pod::Coverage: 1.080
requires:
  Carp: 1.260
  Cwd: 3.400
  Data::Printer: 0.350
  File::Spec: 3.400
  Getopt::Long: 2.390
  MetaCPAN::API: 0.430
  Module::CoreList: 2.840
  Moo: 1.001
  MooX::Types::MooseLike: 0.230
  PPI: 1.215
  Perl::MinimumVersion: 1.320
  Perl::PrereqScanner: 1.015
  Pod::Usage: 1.610
  Scalar::Util: 1.270
  Time::Stamp: 1.300
  Try::Tiny: 0.120
  constant: 1.250
  perl: 5.10.1
  version: 0.990200
resources:
  bugtracker: https://github.com/kevindawson/App-Midgen/issues
  homepage: https://github.com/kevindawson/App-Midgen
  license: http://dev.perl.org/licenses/
  repository: git://github.com/kevindawson/App-Midgen.git
version: 0.14
